import React, { useEffect } from "react";
import { 
  Plane, Calendar, Users, Wallet, Sparkles, MapPin, 
  Sun, Moon, Coffee, Info, CheckCircle2, ChevronRight,
  Clock, ArrowRightLeft, Star, Wind, ThermometerSun
} from "lucide-react";

const C = {
  orange:    "#FF682C",
  navy:      "#0A1E3F",
  navyDeep:  "#061224",
  blue:      "#2D8CFF",
  softWhite: "#F5F7FA",
  textMuted: "#6B7280",
};

export default function TripPlanner() {
  useEffect(() => {
    if (document.getElementById("pt-poppins")) return;
    const l = document.createElement("link");
    l.id = "pt-poppins";
    l.rel = "stylesheet";
    l.href = "https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap";
    document.head.appendChild(l);
  }, []);

  return (
    <div style={{ fontFamily: "'Poppins', sans-serif", backgroundColor: C.softWhite, minHeight: "100vh", paddingBottom: 100 }}>
      {/* Top Header Band */}
      <header style={{
        position: "relative",
        background: `linear-gradient(135deg, ${C.navyDeep} 0%, ${C.navy} 100%)`,
        color: "#fff",
        padding: "60px 0 140px",
        overflow: "hidden"
      }}>
        <div style={{
          position: "absolute", top: 0, right: 0, bottom: 0, width: "50%",
          backgroundImage: "url('/__mockup/images/bali-hero.png')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          opacity: 0.4,
          maskImage: "linear-gradient(to right, transparent, black 40%)",
          WebkitMaskImage: "linear-gradient(to right, transparent, black 40%)"
        }} />
        <div style={{
          position: "absolute", inset: 0,
          background: "linear-gradient(90deg, rgba(6,18,36,1) 0%, rgba(10,30,63,0.8) 50%, rgba(0,0,0,0) 100%)"
        }} />

        <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 40px", position: "relative", zIndex: 10 }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 6, background: "rgba(255,104,44,0.15)", border: `1px solid rgba(255,104,44,0.3)`, padding: "6px 14px", borderRadius: 20, color: C.orange, fontSize: 12, fontWeight: 600, letterSpacing: "0.05em", marginBottom: 20 }}>
            <Sparkles size={14} />
            Generated by Plumtrips AI
          </div>

          <h1 style={{ fontSize: "3.5rem", fontWeight: 700, lineHeight: 1.1, marginBottom: 16, letterSpacing: "-0.02em" }}>
            5 Days in Bali, Indonesia
          </h1>
          <p style={{ fontSize: "1.1rem", color: "rgba(255,255,255,0.7)", maxWidth: 600, marginBottom: 32, lineHeight: 1.6 }}>
            A perfect blend of spiritual culture, lush nature, and luxurious beachside relaxation, curated just for you.
          </p>

          <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, background: "rgba(255,255,255,0.1)", padding: "10px 18px", borderRadius: 12, backdropFilter: "blur(10px)" }}>
              <Calendar size={18} style={{ opacity: 0.7 }} />
              <span style={{ fontSize: 14, fontWeight: 500 }}>Oct 12 - Oct 16 (4 Nights)</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, background: "rgba(255,255,255,0.1)", padding: "10px 18px", borderRadius: 12, backdropFilter: "blur(10px)" }}>
              <Users size={18} style={{ opacity: 0.7 }} />
              <span style={{ fontSize: 14, fontWeight: 500 }}>2 Travelers</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, background: "rgba(255,255,255,0.1)", padding: "10px 18px", borderRadius: 12, backdropFilter: "blur(10px)" }}>
              <Wallet size={18} style={{ opacity: 0.7 }} />
              <span style={{ fontSize: 14, fontWeight: 500 }}>Budget: ₹1,80,000</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, background: "rgba(45,140,255,0.15)", border: `1px solid rgba(45,140,255,0.3)`, padding: "10px 18px", borderRadius: 12, color: "#6DB2FF" }}>
              <Sun size={18} />
              <span style={{ fontSize: 14, fontWeight: 600 }}>Relaxation & Culture</span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content Area */}
      <div style={{ maxWidth: 1280, margin: "-80px auto 0", padding: "0 40px", display: "flex", gap: 32, position: "relative", zIndex: 20, alignItems: "flex-start" }}>
        
        {/* Left Column (Itinerary, Flights, Hotels) */}
        <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 32 }}>
          
          {/* Flights */}
          <section>
            <h2 style={{ fontSize: 22, fontWeight: 700, color: "#fff", marginBottom: 16, display: "flex", alignItems: "center", gap: 10 }}>
              <Plane size={24} color={C.orange} /> Recommended Flights
            </h2>
            <div style={{ background: "#fff", borderRadius: 18, padding: 24, boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
              {/* Outbound */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingBottom: 20, borderBottom: "1px dashed #E5E7EB" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
                  <div style={{ width: 48, height: 48, borderRadius: 12, background: "#F3F4F6", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, color: C.navy }}>AI</div>
                  <div>
                    <div style={{ fontSize: 12, color: C.textMuted, fontWeight: 600, letterSpacing: "0.05em" }}>OUTBOUND • 12 OCT</div>
                    <div style={{ fontSize: 16, fontWeight: 600, color: C.navy }}>Air India (AI-302)</div>
                  </div>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 18, fontWeight: 700, color: C.navy }}>08:30</div>
                    <div style={{ fontSize: 13, color: C.textMuted }}>DEL</div>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", alignItems: "center", width: 100 }}>
                    <div style={{ fontSize: 11, color: C.textMuted, marginBottom: 4 }}>7h 15m</div>
                    <div style={{ width: "100%", height: 2, background: "#E5E7EB", position: "relative" }}>
                      <div style={{ position: "absolute", top: -6, left: "50%", transform: "translateX(-50%)", color: "#9CA3AF" }}><Plane size={14} /></div>
                    </div>
                    <div style={{ fontSize: 11, color: C.textMuted, marginTop: 4 }}>Direct</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 18, fontWeight: 700, color: C.navy }}>17:15</div>
                    <div style={{ fontSize: 13, color: C.textMuted }}>DPS</div>
                  </div>
                  <div style={{ textAlign: "right", paddingLeft: 24, borderLeft: "1px dashed #E5E7EB" }}>
                    <div style={{ fontSize: 18, fontWeight: 800, color: C.orange }}>₹26,000</div>
                    <div style={{ fontSize: 11, color: C.textMuted }}>2 travelers</div>
                  </div>
                </div>
              </div>
              {/* Return */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: 20 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
                  <div style={{ width: 48, height: 48, borderRadius: 12, background: "#F3F4F6", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, color: C.navy }}>AI</div>
                  <div>
                    <div style={{ fontSize: 12, color: C.textMuted, fontWeight: 600, letterSpacing: "0.05em" }}>RETURN • 16 OCT</div>
                    <div style={{ fontSize: 16, fontWeight: 600, color: C.navy }}>Air India (AI-303)</div>
                  </div>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 18, fontWeight: 700, color: C.navy }}>19:00</div>
                    <div style={{ fontSize: 13, color: C.textMuted }}>DPS</div>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", alignItems: "center", width: 100 }}>
                    <div style={{ fontSize: 11, color: C.textMuted, marginBottom: 4 }}>7h 30m</div>
                    <div style={{ width: "100%", height: 2, background: "#E5E7EB", position: "relative" }}>
                      <div style={{ position: "absolute", top: -6, left: "50%", transform: "translateX(-50%)", color: "#9CA3AF" }}><Plane size={14} style={{ transform: "rotate(180deg)" }} /></div>
                    </div>
                    <div style={{ fontSize: 11, color: C.textMuted, marginTop: 4 }}>Direct</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 18, fontWeight: 700, color: C.navy }}>01:00 <span style={{ fontSize: 10, color: C.textMuted }}>+1</span></div>
                    <div style={{ fontSize: 13, color: C.textMuted }}>DEL</div>
                  </div>
                  <div style={{ textAlign: "right", paddingLeft: 24, borderLeft: "1px dashed #E5E7EB" }}>
                    <div style={{ fontSize: 18, fontWeight: 800, color: C.orange }}>₹26,000</div>
                    <div style={{ fontSize: 11, color: C.textMuted }}>2 travelers</div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Hotel */}
          <section>
            <h2 style={{ fontSize: 22, fontWeight: 700, color: C.navy, marginBottom: 16, display: "flex", alignItems: "center", gap: 10 }}>
              <Moon size={24} color={C.orange} /> Where You'll Stay
            </h2>
            <div style={{ background: "#fff", borderRadius: 18, padding: 16, boxShadow: "0 8px 30px rgba(0,0,0,0.04)", display: "flex", gap: 20 }}>
              <div style={{ width: 220, height: 160, borderRadius: 12, overflow: "hidden", flexShrink: 0 }}>
                <img src="/__mockup/images/bali-hotel.png" alt="Hotel" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
              </div>
              <div style={{ display: "flex", flexDirection: "column", justifyContent: "center", flex: 1 }}>
                <div style={{ display: "flex", gap: 4, color: "#FBBF24", marginBottom: 6 }}>
                  {[1,2,3,4,5].map(i => <Star key={i} size={14} fill="currentColor" />)}
                </div>
                <h3 style={{ fontSize: 20, fontWeight: 700, color: C.navy, marginBottom: 4 }}>The Kayon Jungle Resort</h3>
                <div style={{ display: "flex", alignItems: "center", gap: 6, color: C.textMuted, fontSize: 13, marginBottom: 16 }}>
                  <MapPin size={14} /> Ubud, Bali
                </div>
                <div style={{ display: "flex", gap: 12 }}>
                  <span style={{ fontSize: 12, background: "#F3F4F6", padding: "4px 10px", borderRadius: 6, color: C.textMuted, fontWeight: 500 }}>Infinity Pool</span>
                  <span style={{ fontSize: 12, background: "#F3F4F6", padding: "4px 10px", borderRadius: 6, color: C.textMuted, fontWeight: 500 }}>Spa & Wellness</span>
                  <span style={{ fontSize: 12, background: "#F3F4F6", padding: "4px 10px", borderRadius: 6, color: C.textMuted, fontWeight: 500 }}>Breakfast Included</span>
                </div>
              </div>
              <div style={{ display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "flex-end", paddingLeft: 20, borderLeft: "1px dashed #E5E7EB" }}>
                <div style={{ textAlign: "right" }}>
                  <div style={{ fontSize: 12, color: C.textMuted, fontWeight: 600 }}>4 NIGHTS</div>
                  <div style={{ fontSize: 22, fontWeight: 700, color: C.navy }}>₹84,000</div>
                  <div style={{ fontSize: 12, color: C.textMuted }}>inc. taxes</div>
                </div>
                <button style={{ color: C.blue, fontSize: 14, fontWeight: 600, background: "none", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 4 }}>
                  Change Hotel <ChevronRight size={16} />
                </button>
              </div>
            </div>
          </section>

          {/* Itinerary */}
          <section>
            <h2 style={{ fontSize: 22, fontWeight: 700, color: C.navy, marginBottom: 16, display: "flex", alignItems: "center", gap: 10 }}>
              <MapPin size={24} color={C.orange} /> Day-by-Day Itinerary
            </h2>
            
            <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
              {/* Day 1 */}
              <div style={{ background: "#fff", borderRadius: 18, padding: 24, boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                  <div style={{ background: C.navyDeep, color: "#fff", padding: "4px 12px", borderRadius: 8, fontSize: 14, fontWeight: 700 }}>Day 1</div>
                  <h3 style={{ fontSize: 18, fontWeight: 600, color: C.navy }}>Arrival & Relaxation</h3>
                </div>
                
                <div style={{ display: "flex", flexDirection: "column", gap: 20, position: "relative" }}>
                  <div style={{ position: "absolute", left: 15, top: 20, bottom: 20, width: 2, background: "#E5E7EB" }} />
                  
                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Clock size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Afternoon (2:00 PM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Check-in at The Kayon Jungle Resort</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Arrive at DPS airport, meet your private transfer, and head straight to Ubud. Check into your luxury suite and unwind by the iconic infinity pool.</p>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Coffee size={16} />
                    </div>
                    <div style={{ flex: 1, display: "flex", gap: 16 }}>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Evening (7:00 PM)</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Welcome Dinner at Swept Away</div>
                        <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Enjoy a romantic 100-candle dinner experience by the river.</p>
                      </div>
                      <div style={{ width: 100, height: 80, borderRadius: 8, overflow: "hidden", flexShrink: 0 }}>
                        <img src="/__mockup/images/bali-dinner.png" alt="Dinner" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Day 2 */}
              <div style={{ background: "#fff", borderRadius: 18, padding: 24, boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                  <div style={{ background: C.navyDeep, color: "#fff", padding: "4px 12px", borderRadius: 8, fontSize: 14, fontWeight: 700 }}>Day 2</div>
                  <h3 style={{ fontSize: 18, fontWeight: 600, color: C.navy }}>Temples & Terraces</h3>
                </div>
                
                <div style={{ display: "flex", flexDirection: "column", gap: 20, position: "relative" }}>
                  <div style={{ position: "absolute", left: 15, top: 20, bottom: 20, width: 2, background: "#E5E7EB" }} />
                  
                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Sun size={16} />
                    </div>
                    <div style={{ flex: 1, display: "flex", gap: 16 }}>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Morning (9:00 AM)</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Tegallalang Rice Terraces</div>
                        <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Beat the crowds and explore the stunning green terraces. Perfect for photography and a gentle morning walk.</p>
                      </div>
                      <div style={{ width: 100, height: 80, borderRadius: 8, overflow: "hidden", flexShrink: 0 }}>
                        <img src="/__mockup/images/bali-rice-terraces.png" alt="Terraces" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      </div>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Clock size={16} />
                    </div>
                    <div style={{ flex: 1, display: "flex", gap: 16 }}>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Afternoon (2:30 PM)</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Tirta Empul Water Temple</div>
                        <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Participate in a traditional purification ritual in the sacred spring waters.</p>
                      </div>
                      <div style={{ width: 100, height: 80, borderRadius: 8, overflow: "hidden", flexShrink: 0 }}>
                        <img src="/__mockup/images/bali-temple.png" alt="Temple" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      </div>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Moon size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Evening (7:30 PM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Sunset at Campuhan Ridge</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>An easy golden-hour walk along the ridge, followed by a relaxed warung dinner back in central Ubud.</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Day 3 */}
              <div style={{ background: "#fff", borderRadius: 18, padding: 24, boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                  <div style={{ background: C.navyDeep, color: "#fff", padding: "4px 12px", borderRadius: 8, fontSize: 14, fontWeight: 700 }}>Day 3</div>
                  <h3 style={{ fontSize: 18, fontWeight: 600, color: C.navy }}>Beach Club Leisure</h3>
                </div>
                
                <div style={{ display: "flex", flexDirection: "column", gap: 20, position: "relative" }}>
                  <div style={{ position: "absolute", left: 15, top: 20, bottom: 20, width: 2, background: "#E5E7EB" }} />
                  
                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Sun size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Morning (8:00 AM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Sunrise Yoga & Breakfast</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Start the day with a guided open-air yoga session, then a slow tropical breakfast before heading to the coast.</p>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Sun size={16} />
                    </div>
                    <div style={{ flex: 1, display: "flex", gap: 16 }}>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Afternoon (1:00 PM)</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Finns Beach Club VIP Access</div>
                        <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Lounge on a VIP daybed, enjoy premium cocktails, and swim in the oceanfront infinity pools.</p>
                      </div>
                      <div style={{ width: 100, height: 80, borderRadius: 8, overflow: "hidden", flexShrink: 0 }}>
                        <img src="/__mockup/images/bali-beach.png" alt="Beach" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      </div>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Moon size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Evening (6:30 PM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Seafood Dinner on Jimbaran Bay</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Toes-in-the-sand grilled seafood as the sun sets over the bay — a Bali classic.</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Day 4 */}
              <div style={{ background: "#fff", borderRadius: 18, padding: 24, boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                  <div style={{ background: C.navyDeep, color: "#fff", padding: "4px 12px", borderRadius: 8, fontSize: 14, fontWeight: 700 }}>Day 4</div>
                  <h3 style={{ fontSize: 18, fontWeight: 600, color: C.navy }}>Waterfalls & Wellness</h3>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: 20, position: "relative" }}>
                  <div style={{ position: "absolute", left: 15, top: 20, bottom: 20, width: 2, background: "#E5E7EB" }} />

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Sun size={16} />
                    </div>
                    <div style={{ flex: 1, display: "flex", gap: 16 }}>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Morning (8:30 AM)</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Tegenungan Waterfall</div>
                        <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Take an early private transfer to one of Bali's most photogenic waterfalls and cool off before the crowds arrive.</p>
                      </div>
                      <div style={{ width: 100, height: 80, borderRadius: 8, overflow: "hidden", flexShrink: 0 }}>
                        <img src="/__mockup/images/bali-rice-terraces.png" alt="Waterfall" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      </div>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Moon size={16} />
                    </div>
                    <div style={{ flex: 1, display: "flex", gap: 16 }}>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Afternoon (3:00 PM)</div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Signature Balinese Spa Ritual</div>
                        <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>A two-hour couples' spa journey at the resort — flower bath, hot-stone massage, and herbal tea on your private deck.</p>
                      </div>
                      <div style={{ width: 100, height: 80, borderRadius: 8, overflow: "hidden", flexShrink: 0 }}>
                        <img src="/__mockup/images/bali-hotel.png" alt="Spa" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      </div>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Coffee size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Evening (7:00 PM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Private Chef's Table Dinner</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>A multi-course Indonesian tasting menu prepared by the resort's private chef, paired with local wines.</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Day 5 */}
              <div style={{ background: "#fff", borderRadius: 18, padding: 24, boxShadow: "0 8px 30px rgba(0,0,0,0.04)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                  <div style={{ background: C.navyDeep, color: "#fff", padding: "4px 12px", borderRadius: 8, fontSize: 14, fontWeight: 700 }}>Day 5</div>
                  <h3 style={{ fontSize: 18, fontWeight: 600, color: C.navy }}>Farewell Bali</h3>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: 20, position: "relative" }}>
                  <div style={{ position: "absolute", left: 15, top: 20, bottom: 20, width: 2, background: "#E5E7EB" }} />

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Sun size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Morning (10:00 AM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Ubud Art Market & Café Breakfast</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Late check-out, a leisurely breakfast, and last-minute souvenir shopping for handmade crafts at the Ubud Art Market.</p>
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 20, position: "relative", zIndex: 2 }}>
                    <div style={{ width: 32, height: 32, borderRadius: "50%", background: C.softWhite, border: "2px solid #E5E7EB", display: "flex", alignItems: "center", justifyContent: "center", color: C.textMuted, flexShrink: 0 }}>
                      <Plane size={16} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: C.navy }}>Evening (4:00 PM)</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 4 }}>Private Transfer to DPS Airport</div>
                      <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>Relax on the drive back to Denpasar in time for your 19:00 return flight home.</p>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </section>

          {/* Good to know */}
          <section style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
            <div style={{ background: "rgba(45,140,255,0.05)", border: "1px solid rgba(45,140,255,0.2)", borderRadius: 16, padding: 20 }}>
              <h4 style={{ fontSize: 16, fontWeight: 600, color: C.navy, marginBottom: 12, display: "flex", alignItems: "center", gap: 8 }}>
                <ThermometerSun size={18} color={C.blue} /> Weather in Oct
              </h4>
              <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>
                Expect warm, sunny days around 28°C (82°F). It's the tail end of the dry season, making it perfect for both beach days and jungle treks.
              </p>
            </div>
            <div style={{ background: "rgba(255,104,44,0.05)", border: "1px solid rgba(255,104,44,0.2)", borderRadius: 16, padding: 20 }}>
              <h4 style={{ fontSize: 16, fontWeight: 600, color: C.navy, marginBottom: 12, display: "flex", alignItems: "center", gap: 8 }}>
                <Info size={18} color={C.orange} /> Local Tips
              </h4>
              <p style={{ fontSize: 14, color: C.textMuted, lineHeight: 1.5 }}>
                Dress modestly when visiting temples (sarongs provided). Carry small IDR cash notes for tipping and small purchases.
              </p>
            </div>
          </section>
        </div>

        {/* Right Column (Sticky Booking Sidebar) */}
        <div style={{ width: 380, flexShrink: 0, position: "sticky", top: 40 }}>
          <div style={{ background: "#fff", borderRadius: 20, padding: 28, boxShadow: "0 12px 40px rgba(0,0,0,0.06)", border: "1px solid #E5E7EB" }}>
            <h3 style={{ fontSize: 20, fontWeight: 700, color: C.navy, marginBottom: 20 }}>Trip Cost Summary</h3>
            
            <div style={{ display: "flex", flexDirection: "column", gap: 12, marginBottom: 24 }}>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 14, color: C.textMuted }}>
                <span>Flights (2 pax)</span>
                <span style={{ fontWeight: 600, color: C.navy }}>₹52,000</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 14, color: C.textMuted }}>
                <span>Hotel (4 nights)</span>
                <span style={{ fontWeight: 600, color: C.navy }}>₹84,000</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 14, color: C.textMuted }}>
                <span>Activities & Passes</span>
                <span style={{ fontWeight: 600, color: C.navy }}>₹18,500</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 14, color: C.textMuted }}>
                <span>Private Transfers</span>
                <span style={{ fontWeight: 600, color: C.navy }}>₹8,000</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 14, color: C.textMuted }}>
                <span>Taxes & Fees</span>
                <span style={{ fontWeight: 600, color: C.navy }}>₹9,800</span>
              </div>
            </div>

            <div style={{ height: 1, background: "#E5E7EB", marginBottom: 20 }} />

            <div style={{ marginBottom: 24 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 4 }}>
                <span style={{ fontSize: 16, fontWeight: 600, color: C.navy }}>Total Estimate</span>
                <span style={{ fontSize: 28, fontWeight: 800, color: C.orange, lineHeight: 1 }}>₹1,72,300</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 4, color: "#10B981", fontSize: 12, fontWeight: 600, background: "rgba(16,185,129,0.1)", padding: "4px 8px", borderRadius: 6 }}>
                  <CheckCircle2 size={14} /> ₹7,700 under budget
                </div>
                <span style={{ fontSize: 12, color: C.textMuted }}>₹86,150 / person</span>
              </div>
            </div>

            <button style={{ width: "100%", background: C.orange, color: "#fff", border: "none", padding: "16px", borderRadius: 12, fontSize: 16, fontWeight: 700, cursor: "pointer", boxShadow: "0 8px 20px rgba(255,104,44,0.3)", display: "flex", justifyContent: "center", alignItems: "center", gap: 8, transition: "transform 0.2s", marginBottom: 16 }}>
              Book This Trip <ChevronRight size={18} />
            </button>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
              <button style={{ background: "#F3F4F6", color: C.navy, border: "none", padding: "12px", borderRadius: 10, fontSize: 14, fontWeight: 600, cursor: "pointer", transition: "background 0.2s" }}>
                Customize
              </button>
              <button style={{ background: "#F3F4F6", color: C.navy, border: "none", padding: "12px", borderRadius: 10, fontSize: 14, fontWeight: 600, cursor: "pointer", transition: "background 0.2s" }}>
                Save Plan
              </button>
            </div>
            
            <div style={{ textAlign: "center", marginTop: 16 }}>
              <button style={{ background: "none", border: "none", color: C.blue, fontSize: 13, fontWeight: 500, cursor: "pointer" }}>
                ⟲ Regenerate Plan
              </button>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}
